version: "3.8"
services:
  db:
    image: postgres:9.4
    container_name: social_out_db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: social_out_api
    ports: 
      - ${API_PORT}:${API_PORT}
    environment:
      API_PORT: ${API_PORT}
      API_DEBUG: ${API_DEBUG}
      API_SECRET_KEY: ${API_SECRET_KEY}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 5s
volumes:
  pgdata:
    driver: local