"""empty message

Revision ID: 18efac3c2175
Revises: 4ef6acb07c19
Create Date: 2022-05-18 13:45:05.104696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18efac3c2175'
down_revision = '4ef6acb07c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_eventid_fkey', 'message', type_='foreignkey')
    op.drop_constraint('message_userid_fkey', 'message', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('message_userid_fkey', 'message', 'users', ['userid'], ['id'])
    op.create_foreign_key('message_eventid_fkey', 'message', 'events', ['eventid'], ['id'])
    # ### end Alembic commands ###
