"""empty message

Revision ID: 1da99e31486f
Revises: 33b1abe1ac84
Create Date: 2022-05-30 21:29:13.376280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1da99e31486f'
down_revision = '33b1abe1ac84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_model',
    sa.Column('ml_model_bytes', postgresql.BYTEA(), nullable=False),
    sa.PrimaryKeyConstraint('ml_model_bytes')
    )
    op.add_column('air_quality_station', sa.Column('codi_comarca', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('air_quality_station', 'codi_comarca')
    op.drop_table('ml_model')
    # ### end Alembic commands ###
