"""empty message

Revision ID: 33b1abe1ac84
Revises: 6195b4c6d85a
Create Date: 2022-05-28 13:39:07.195643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b1abe1ac84'
down_revision = '6195b4c6d85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chat', 'users', ['creador_id'], ['id'])
    op.create_foreign_key(None, 'chat', 'events', ['event_id'], ['id'])
    op.create_foreign_key(None, 'chat', 'users', ['participant_id'], ['id'])
    op.create_foreign_key(None, 'message', 'users', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_constraint(None, 'chat', type_='foreignkey')
    op.drop_constraint(None, 'chat', type_='foreignkey')
    # ### end Alembic commands ###
