"""empty message

Revision ID: 540ed16b96fe
Revises: 244c68c80a2c
Create Date: 2022-03-16 20:52:04.486916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540ed16b96fe'
down_revision = '244c68c80a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SocialMedia',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SocialMedia')
    # ### end Alembic commands ###
