"""empty message

Revision ID: 6e97ec140b18
Revises: 18efac3c2175
Create Date: 2022-05-21 12:03:12.746497

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6e97ec140b18'
down_revision = '18efac3c2175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('event_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('participant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('message', sa.Column('sender_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('message', sa.Column('chat_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'message', 'chat', ['chat_id'], ['id'])
    op.drop_column('message', 'eventid')
    op.drop_column('message', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('userid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('message', sa.Column('eventid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'chat_id')
    op.drop_column('message', 'sender_id')
    op.drop_table('chat')
    # ### end Alembic commands ###
