"""empty message

Revision ID: 813c6a0f5a33
Revises: 
Create Date: 2022-05-14 18:39:43.461525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '813c6a0f5a33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('likes',
    sa.Column('event_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.add_column('events', sa.Column('date_creation', sa.DateTime(), nullable=False))
    op.drop_constraint('facebook_auth_facebook_id_key', 'facebook_auth', type_='unique')
    op.drop_column('facebook_auth', 'facebook_id')
    op.drop_constraint('google_auth_google_id_key', 'google_auth', type_='unique')
    op.drop_column('google_auth', 'google_id')
    op.add_column('users', sa.Column('hobbies', sa.String(), nullable=False))
    op.alter_column('users', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'hobbies')
    op.add_column('google_auth', sa.Column('google_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('google_auth_google_id_key', 'google_auth', ['google_id'])
    op.add_column('facebook_auth', sa.Column('facebook_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('facebook_auth_facebook_id_key', 'facebook_auth', ['facebook_id'])
    op.drop_column('events', 'date_creation')
    op.drop_table('likes')
    op.drop_table('email_verification')
    # ### end Alembic commands ###
