"""empty message

Revision ID: 945ec48fbf17
Revises: 6e97ec140b18
Create Date: 2022-05-24 16:43:29.670292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '945ec48fbf17'
down_revision = '6e97ec140b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('creador_id', postgresql.UUID(as_uuid=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'creador_id')
    # ### end Alembic commands ###
