"""empty message
Revision ID: e617fb9b361f
Revises: 
Create Date: 2022-03-29 19:55:24.759997
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e617fb9b361f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_quality_station',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('eoi_code', sa.String(), nullable=False),
    sa.Column('station_type', sa.Enum('traffic', 'background', 'industrial', name='station_type'), nullable=True),
    sa.Column('urban_area', sa.Enum('urban', 'periurban', 'suburban', 'rural', name='urban_area'), nullable=True),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('air_condition_scale', sa.Float(), nullable=True),
    sa.Column('time_computation_scale', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('eoi_code')
    )
    op.create_table('events',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_started', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('user_creator', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pollutant',
    sa.Column('composition', sa.String(), nullable=False),
    sa.Column('common_lowerbound', sa.Float(), nullable=True),
    sa.Column('common_upperbound', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('air_quality_weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('composition')
    )
    op.create_table('air_quality_data',
    sa.Column('date_hour', sa.DateTime(), nullable=False),
    sa.Column('station_eoi_code', sa.String(), nullable=False),
    sa.Column('pollutant_composition', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('contaminant_scale', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pollutant_composition'], ['pollutant.composition'], ),
    sa.ForeignKeyConstraint(['station_eoi_code'], ['air_quality_station.eoi_code'], ),
    sa.PrimaryKeyConstraint('date_hour', 'station_eoi_code', 'pollutant_composition')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('air_quality_data')
    op.drop_table('pollutant')
    op.drop_table('events')
    op.drop_table('air_quality_station')
    # ### end Alembic commands ###
