"""empty message

Revision ID: 7e93a9e91d50
Revises: 
Create Date: 2022-03-23 19:44:47.011232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e93a9e91d50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AirQualityStation',
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('EOIcode', sa.String(), nullable=False),
    sa.Column('StationType', sa.Enum('TRAFFIC', 'BACKGROUND', 'INDUSTRIAL', name='stationtype'), nullable=True),
    sa.Column('UrbanArea', sa.Enum('URBAN', 'PERIURBAN', 'RURAL', name='urbanarea'), nullable=True),
    sa.Column('Height', sa.Integer(), nullable=True),
    sa.Column('GeoReference', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('EOIcode')
    )
    op.create_table('DateHour',
    sa.Column('DateHour', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('DateHour')
    )
    op.create_table('AirQualityData',
    sa.Column('DateHour', sa.DateTime(), nullable=False),
    sa.Column('EOIcodeStation', sa.String(), nullable=False),
    sa.Column('Magnitude', sa.Integer(), nullable=True),
    sa.Column('PollutantComposition', sa.String(), nullable=True),
    sa.Column('Units', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['DateHour'], ['DateHour.DateHour'], ),
    sa.ForeignKeyConstraint(['EOIcodeStation'], ['AirQualityStation.EOIcode'], ),
    sa.PrimaryKeyConstraint('DateHour', 'EOIcodeStation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AirQualityData')
    op.drop_table('DateHour')
    op.drop_table('AirQualityStation')
    # ### end Alembic commands ###
