"""empty message

Revision ID: 8841f6bd2805
Revises: e617fb9b361f
Create Date: 2022-04-06 19:39:05.569512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8841f6bd2805'
down_revision = 'e617fb9b361f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tri_cache',
    sa.Column('date_hour', sa.DateTime(), nullable=False),
    sa.Column('tri_object_bytes', postgresql.BYTEA(), nullable=True),
    sa.PrimaryKeyConstraint('date_hour')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tri_cache')
    # ### end Alembic commands ###
