name: Develop Testing - API Flask Python

on:
  push:
    branches:
      - develop
      - main
      - 'release/**'
    paths-ignore:
      - '**README.md'
  pull_request:
    branches:
      - develop
      - main
      - 'release/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r api/requirements.txt
          echo "PYTHONPATH=mlprepare" >> $GITHUB_ENV
      - name: Analize static code with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 api/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 api/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest api/test --doctest-modules --junitxml=junit/test-results.xml